In [1]:
import torch

In [2]:
t = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])


#### Methods to Extract column of 1-D Tensor from a given tensor
##### 1. unbind

    torch.unbind(tensor, dim=0)

Removes a tensor dimension.

Returns a tuple of all slices along a given dimension, already without it.

Parameters: 

            tensor (Tensor) – the tensor to unbind

            dim (int) – dimension to remove (for a 2-d tensor 0 means row wise, 1 means column wise)

In [3]:
col1 = torch.unbind(t,1)[1]
print(col1)

tensor([ 2.,  5.,  8.])


##### 2. numpy style indexing
pytorch ternsors support numpy indexing too.

    subset = t[ row_start : row_end , column_start:column_end]

In [4]:
col2 = t[:,1:1]
print(col2)

tensor([ 2.,  5.,  8.])


##### 3. Transpose

In [5]:

col3 =  torch.t(t)[1,:]
print(col3)

tensor([ 2.,  5.,  8.])


##### 4 index_select

    torch.index_select(input, dim, index, out=None)

Returns a new tensor which indexes the input tensor along dimension dim using the entries in index which is a LongTensor.

The returned tensor has the same number of dimensions as the original tensor (input). The dimth dimension has the same size as the length of index; other dimensions have the same size as in the original tensor.

Parameters:

    input (Tensor) – the input tensor
    dim (int) – the dimension in which we index
    index (LongTensor) – the 1-D tensor containing the indices to index
    out (Tensor, optional) – the output tensor

In [6]:
col4 = torch.index_select(t, 1, torch.LongTensor([1]))
print(col4)

tensor([[ 2.],
        [ 5.],
        [ 8.]])


In [7]:
print('-' * 80)
print('|Method', '\t\t\t|','DataType', '\t\t\t|', 'Dimension\t|')
print('-' * 80)
print('|unbind', '\t\t\t|',type(col1), '\t|',col1.dim(),'\t\t|')
print('|numpy style indexing', '\t\t|',type(col2), '\t|',col2.dim(),'\t\t|')
print('|Transpose', '\t\t\t|',type(col3), '\t|',col3.dim(),'\t\t|')
print('\033[91m|index_select', '\t\t\t|',type(col4), '\t|',col4.dim(),'\t\t|','\033[0m')
print('-' * 80)

--------------------------------------------------------------------------------
|Method 			| DataType 			| Dimension	|
--------------------------------------------------------------------------------
|unbind 			| <class 'torch.Tensor'> 	| 1 		|
|numpy style indexing 		| <class 'torch.Tensor'> 	| 1 		|
|Transpose 			| <class 'torch.Tensor'> 	| 1 		|
|index_select 			| <class 'torch.Tensor'> 	| 2 		| 
--------------------------------------------------------------------------------


From the above table we notice that the only first 3 methods resulted in the 1-Dimensional tensor as per the requirement, whereas the last method resulted in 2-Dimensional tensor.

### Difference between Tensor, storage and variable

#### Tensor
To breif about tensor, first we must understand basic concepts.

        A Scalar is a representation of value.
        A Vector is a collection or 1-D array of scalars values.
        A Matrix is a 2-D array or collection of Vectors of similar length arranged horizontally or vertically.
        A Tensor is a Multi-Dimensional collection of matrices.

        A Tensor is a particular way of viewing a Storage.

#### Storage 
        Storage in simple terms is a memory holder in programming language. Be it a value of variable or object. In Torch, Storage is way to access memory of an array. The actual data of a Tensor is located in a Storage.
    
        As the memory of a Tensor has to be contained in unique Storage, it might not be contiguous.
    
        A Storage only represents a chunk of memory, while Tensor interprets this chunk of memory with dimensions.
    
#### Variable

        A Variable wraps a tensor and records the operations applied to it. It also holds the gradient w.r.t. to a tensor, and a reference to a function that created a variable.
    
        A Variable allows to perform automatic differentiation, which is generating gradient computation to entire computation graph which offers better system optimization.
    
    